name: rapid_rescue
description: "One stop destination of Ambulance"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  http:
  fluttertoast: ^8.2.4
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#f7bf50"
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"

flutter:
  uses-material-design: true
