name: rapid_rescue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  http:
  fluttertoast: ^8.2.4
  flutter:
    sdk: flutter
  geolocator: ^8.2.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
